"""
ui_strings.py — Multi-Language Interface Strings
─────────────────────────────────────────────────
UI text for 8 interface languages.
To add more: copy any block and translate all values.
"""

UI_STRINGS = {
    "English": {
        "page_title":"Pic2Docs — Image to Text Converter",
        "tagline":"Image → Editable Text → Any Format",
        "hero_title":"Convert Any Image to Editable Text — Instantly",
        "hero_desc":"Upload handwritten notes, printed documents, receipts, or books.\nPic2Docs extracts text with AI-powered OCR and exports in any format.",
        "upload_section":"Upload Image","upload_label":"Drop your image here or click to browse",
        "settings_section":"Settings","ocr_lang_label":"OCR Language",
        "ocr_lang_help":"Select the language of text in your image.",
        "preprocess_label":"Apply image enhancement",
        "preprocess_help":"Recommended for low-contrast or skewed images.",
        "preprocess_desc":"Applies contrast correction, sharpening, and adaptive threshold.",
        "extract_btn":"🔍 Extract Text","extracting":"Running OCR — up to 30 seconds...",
        "extract_success":"✅ Extracted {blocks} blocks with {conf}% confidence.",
        "file_too_large":"File exceeds {max_mb} MB. Please compress.",
        "no_upload_title":"Upload an image to get started",
        "no_upload_desc":"Works best with clear, well-lit images.",
        "extracted_section":"Extracted Text — Edit Before Exporting",
        "reset_btn":"↩ Reset","clear_btn":"🗑 Clear all",
        "export_section":"Export","nothing_to_export":"Nothing to export — text is empty.",
        "translate_section":"Translate","translate_to":"Translate to",
        "translate_placeholder":"— Select language —","translate_btn":"🌐 Translate",
        "translating":"Translating to {lang}...","translate_success":"Translation complete!",
        "translate_fail":"Translation failed: {err}","translated_label":"Translated ({lang})",
        "dl_txt":"📃 TXT","dl_pdf":"📄 PDF","dl_word":"📝 Word","dl_excel":"📊 Excel","dl_notebook":"🖼 Notebook",
        "dl_trans_txt":"📃 TXT","dl_trans_pdf":"📄 PDF",
        "how_it_works":"How It Works",
        "empty_state_title":"Your extracted text will appear here",
        "empty_state_desc":"Upload an image and click Extract Text.",
        "footer":"{app} v{ver} · EasyOCR · fpdf2 · python-docx · deep-translator · All processing is local.",
        "conf_high":"High","conf_med":"Medium","conf_low":"Low","conf_label":"Confidence — ",
        "stat_words":"words","stat_lines":"lines","stat_chars":"chars","stat_blocks":"blocks","stat_lang":"lang",
        "no_text_detected":"No text detected. Try a clearer image.",
        "translate_empty":"Extract text first to enable translation.",
        "ui_lang_label":"Interface Language",
        "steps":[
            ("1️⃣","Upload","PNG, JPG, WEBP, BMP, TIFF — up to 10 MB"),
            ("2️⃣","Select","Choose the language of text in your image"),
            ("3️⃣","Extract","AI OCR reads printed & handwritten text"),
            ("4️⃣","Edit","Fix errors in the editable text area"),
            ("5️⃣","Export","Download as TXT, PDF, Word, Excel, or PNG"),
            ("6️⃣","Translate","Translate your text into 30 languages"),
        ],
    },
    "Hindi": {
        "page_title":"Pic2Docs — इमेज से टेक्स्ट",
        "tagline":"इमेज → टेक्स्ट → कोई भी फॉर्मेट",
        "hero_title":"किसी भी इमेज को तुरंत टेक्स्ट में बदलें",
        "hero_desc":"हस्तलिखित नोट्स, प्रिंटेड दस्तावेज़ या रसीदें अपलोड करें।\nPic2Docs AI-OCR से टेक्स्ट निकालता है।",
        "upload_section":"इमेज अपलोड","upload_label":"यहाँ इमेज छोड़ें या Browse करें",
        "settings_section":"सेटिंग्स","ocr_lang_label":"OCR भाषा",
        "ocr_lang_help":"इमेज में टेक्स्ट की भाषा चुनें।",
        "preprocess_label":"इमेज एन्हांसमेंट",
        "preprocess_help":"कम रोशनी वाली इमेज के लिए अनुशंसित।",
        "preprocess_desc":"कंट्रास्ट, शार्पनिंग और adaptive threshold लागू करता है।",
        "extract_btn":"🔍 टेक्स्ट निकालें","extracting":"OCR चल रहा है — 30 सेकंड...",
        "extract_success":"✅ {blocks} ब्लॉक निकाले — {conf}% आत्मविश्वास।",
        "file_too_large":"फ़ाइल {max_mb} MB से बड़ी है।",
        "no_upload_title":"शुरू करने के लिए इमेज अपलोड करें",
        "no_upload_desc":"स्पष्ट, अच्छी रोशनी वाली इमेज बेहतर काम करती है।",
        "extracted_section":"निकाला गया टेक्स्ट — संपादित करें",
        "reset_btn":"↩ रीसेट","clear_btn":"🗑 साफ़ करें",
        "export_section":"एक्सपोर्ट","nothing_to_export":"एक्सपोर्ट के लिए कुछ नहीं।",
        "translate_section":"अनुवाद","translate_to":"इसमें अनुवाद करें",
        "translate_placeholder":"— भाषा चुनें —","translate_btn":"🌐 अनुवाद करें",
        "translating":"{lang} में अनुवाद...","translate_success":"अनुवाद पूरा!",
        "translate_fail":"अनुवाद विफल: {err}","translated_label":"अनुवाद ({lang})",
        "dl_txt":"📃 TXT","dl_pdf":"📄 PDF","dl_word":"📝 Word","dl_excel":"📊 Excel","dl_notebook":"🖼 Notebook",
        "dl_trans_txt":"📃 TXT","dl_trans_pdf":"📄 PDF",
        "how_it_works":"यह कैसे काम करता है",
        "empty_state_title":"आपका टेक्स्ट यहाँ दिखेगा",
        "empty_state_desc":"इमेज अपलोड करें और टेक्स्ट निकालें पर क्लिक करें।",
        "footer":"{app} v{ver} · EasyOCR · सभी प्रोसेसिंग स्थानीय।",
        "conf_high":"उच्च","conf_med":"मध्यम","conf_low":"निम्न","conf_label":"विश्वास — ",
        "stat_words":"शब्द","stat_lines":"पंक्तियाँ","stat_chars":"अक्षर","stat_blocks":"ब्लॉक","stat_lang":"भाषा",
        "no_text_detected":"कोई टेक्स्ट नहीं मिला। स्पष्ट इमेज आज़माएं।",
        "translate_empty":"पहले टेक्स्ट निकालें।",
        "ui_lang_label":"इंटरफ़ेस भाषा",
        "steps":[
            ("1️⃣","अपलोड","PNG, JPG, WEBP, BMP, TIFF — 10 MB तक"),
            ("2️⃣","चुनें","इमेज में टेक्स्ट की भाषा चुनें"),
            ("3️⃣","निकालें","AI OCR प्रिंटेड और हस्तलिखित पढ़ता है"),
            ("4️⃣","संपादित करें","गलतियाँ ठीक करें"),
            ("5️⃣","एक्सपोर्ट","TXT, PDF, Word, Excel या PNG"),
            ("6️⃣","अनुवाद","30 भाषाओं में अनुवाद"),
        ],
    },
    "Urdu": {
        "page_title":"Pic2Docs — تصویر سے متن",
        "tagline":"تصویر ← متن ← کوئی فارمیٹ",
        "hero_title":"کسی بھی تصویر کو فوری متن میں بدلیں",
        "hero_desc":"ہاتھ سے لکھے نوٹس یا پرنٹ دستاویزات اپ لوڈ کریں۔\nPic2Docs AI-OCR سے متن نکالتا ہے۔",
        "upload_section":"تصویر اپ لوڈ","upload_label":"یہاں ڈراپ کریں یا Browse کریں",
        "settings_section":"ترتیبات","ocr_lang_label":"OCR زبان",
        "ocr_lang_help":"تصویر میں متن کی زبان منتخب کریں۔",
        "preprocess_label":"تصویر بہتری",
        "preprocess_help":"کم روشنی والی تصاویر کے لیے تجویز کردہ۔",
        "preprocess_desc":"کنٹراسٹ، شارپننگ اور adaptive threshold۔",
        "extract_btn":"🔍 متن نکالیں","extracting":"OCR چل رہا ہے — 30 سیکنڈ...",
        "extract_success":"✅ {blocks} بلاکس — {conf}% اعتماد۔",
        "file_too_large":"فائل {max_mb} MB سے بڑی ہے۔",
        "no_upload_title":"شروع کرنے کے لیے تصویر اپ لوڈ کریں",
        "no_upload_desc":"واضح، اچھی روشنی والی تصویر بہتر ہے۔",
        "extracted_section":"نکالا گیا متن — ترمیم کریں",
        "reset_btn":"↩ ری سیٹ","clear_btn":"🗑 صاف کریں",
        "export_section":"برآمد","nothing_to_export":"برآمد کے لیے کچھ نہیں۔",
        "translate_section":"ترجمہ","translate_to":"ترجمہ کریں",
        "translate_placeholder":"— زبان منتخب کریں —","translate_btn":"🌐 ترجمہ",
        "translating":"{lang} میں ترجمہ...","translate_success":"ترجمہ مکمل!",
        "translate_fail":"ترجمہ ناکام: {err}","translated_label":"ترجمہ ({lang})",
        "dl_txt":"📃 TXT","dl_pdf":"📄 PDF","dl_word":"📝 Word","dl_excel":"📊 Excel","dl_notebook":"🖼 Notebook",
        "dl_trans_txt":"📃 TXT","dl_trans_pdf":"📄 PDF",
        "how_it_works":"یہ کیسے کام کرتا ہے",
        "empty_state_title":"آپ کا متن یہاں دکھے گا",
        "empty_state_desc":"تصویر اپ لوڈ کریں اور متن نکالیں پر کلک کریں۔",
        "footer":"{app} v{ver} · EasyOCR · تمام پروسیسنگ مقامی۔",
        "conf_high":"بلند","conf_med":"درمیانہ","conf_low":"کم","conf_label":"اعتماد — ",
        "stat_words":"الفاظ","stat_lines":"سطریں","stat_chars":"حروف","stat_blocks":"بلاکس","stat_lang":"زبان",
        "no_text_detected":"کوئی متن نہیں ملا۔ واضح تصویر آزمائیں۔",
        "translate_empty":"پہلے متن نکالیں۔",
        "ui_lang_label":"انٹرفیس زبان",
        "steps":[
            ("1️⃣","اپ لوڈ","PNG, JPG, WEBP — 10 MB تک"),
            ("2️⃣","منتخب","زبان چنیں"),
            ("3️⃣","نکالیں","AI OCR پڑھتا ہے"),
            ("4️⃣","ترمیم","غلطیاں ٹھیک کریں"),
            ("5️⃣","برآمد","TXT, PDF, Word, Excel"),
            ("6️⃣","ترجمہ","30 زبانوں میں ترجمہ"),
        ],
    },
    "Arabic": {
        "page_title":"Pic2Docs — محوّل الصورة إلى نص",
        "tagline":"صورة ← نص ← أي تنسيق",
        "hero_title":"حوّل أي صورة إلى نص — فوراً",
        "hero_desc":"ارفع ملاحظات مكتوبة أو مستندات مطبوعة.\nيستخرج Pic2Docs النص بتقنية OCR الذكية.",
        "upload_section":"رفع صورة","upload_label":"أسقط الصورة هنا أو انقر",
        "settings_section":"الإعدادات","ocr_lang_label":"لغة OCR",
        "ocr_lang_help":"اختر لغة النص في الصورة.",
        "preprocess_label":"تحسين الصورة",
        "preprocess_help":"موصى به للصور ذات التباين المنخفض.",
        "preprocess_desc":"تصحيح التباين والحدة والعتبة التكيّفية.",
        "extract_btn":"🔍 استخراج النص","extracting":"جارٍ OCR — حتى 30 ثانية...",
        "extract_success":"✅ {blocks} كتلة بثقة {conf}%.",
        "file_too_large":"الملف يتجاوز {max_mb} ميجابايت.",
        "no_upload_title":"ارفع صورة للبدء",
        "no_upload_desc":"يعمل أفضل مع صور واضحة.",
        "extracted_section":"النص المستخرج — حرّره",
        "reset_btn":"↩ إعادة تعيين","clear_btn":"🗑 مسح",
        "export_section":"تصدير","nothing_to_export":"لا شيء للتصدير.",
        "translate_section":"ترجمة","translate_to":"ترجمة إلى",
        "translate_placeholder":"— اختر اللغة —","translate_btn":"🌐 ترجمة",
        "translating":"ترجمة إلى {lang}...","translate_success":"اكتملت الترجمة!",
        "translate_fail":"فشلت: {err}","translated_label":"مترجم ({lang})",
        "dl_txt":"📃 TXT","dl_pdf":"📄 PDF","dl_word":"📝 Word","dl_excel":"📊 Excel","dl_notebook":"🖼 Notebook",
        "dl_trans_txt":"📃 TXT","dl_trans_pdf":"📄 PDF",
        "how_it_works":"كيف يعمل",
        "empty_state_title":"سيظهر نصك هنا",
        "empty_state_desc":"ارفع صورة واضغط استخراج.",
        "footer":"{app} v{ver} · EasyOCR · معالجة محلية.",
        "conf_high":"عالية","conf_med":"متوسطة","conf_low":"منخفضة","conf_label":"ثقة — ",
        "stat_words":"كلمات","stat_lines":"أسطر","stat_chars":"أحرف","stat_blocks":"كتل","stat_lang":"اللغة",
        "no_text_detected":"لم يتم اكتشاف نص. جرّب صورة أوضح.",
        "translate_empty":"استخرج النص أولاً.",
        "ui_lang_label":"لغة الواجهة",
        "steps":[
            ("1️⃣","رفع","PNG, JPG, WEBP — حتى 10 MB"),
            ("2️⃣","اختيار","اختر لغة النص"),
            ("3️⃣","استخراج","OCR يقرأ المطبوع والمكتوب"),
            ("4️⃣","تحرير","صحّح الأخطاء"),
            ("5️⃣","تصدير","TXT, PDF, Word, Excel"),
            ("6️⃣","ترجمة","ترجم إلى 30 لغة"),
        ],
    },
    "French": {
        "page_title":"Pic2Docs — Convertisseur Image vers Texte",
        "tagline":"Image → Texte → N'importe quel format",
        "hero_title":"Convertissez n'importe quelle image en texte — Instantanément",
        "hero_desc":"Téléchargez notes manuscrites, documents imprimés ou reçus.\nPic2Docs extrait le texte avec l'OCR IA.",
        "upload_section":"Télécharger","upload_label":"Déposez ici ou cliquez pour parcourir",
        "settings_section":"Paramètres","ocr_lang_label":"Langue OCR",
        "ocr_lang_help":"Sélectionnez la langue du texte dans l'image.",
        "preprocess_label":"Amélioration d'image",
        "preprocess_help":"Recommandé pour les images à faible contraste.",
        "preprocess_desc":"Contraste, netteté et seuillage adaptatif.",
        "extract_btn":"🔍 Extraire","extracting":"OCR en cours — 30 secondes...",
        "extract_success":"✅ {blocks} blocs extraits à {conf}%.",
        "file_too_large":"Fichier > {max_mb} Mo. Compressez l'image.",
        "no_upload_title":"Téléchargez une image pour commencer",
        "no_upload_desc":"Meilleures performances avec des images claires.",
        "extracted_section":"Texte extrait — Modifiez avant d'exporter",
        "reset_btn":"↩ Réinitialiser","clear_btn":"🗑 Effacer",
        "export_section":"Exporter","nothing_to_export":"Rien à exporter.",
        "translate_section":"Traduire","translate_to":"Traduire en",
        "translate_placeholder":"— Sélectionner —","translate_btn":"🌐 Traduire",
        "translating":"Traduction en {lang}...","translate_success":"Traduction terminée !",
        "translate_fail":"Échec : {err}","translated_label":"Traduit ({lang})",
        "dl_txt":"📃 TXT","dl_pdf":"📄 PDF","dl_word":"📝 Word","dl_excel":"📊 Excel","dl_notebook":"🖼 Notebook",
        "dl_trans_txt":"📃 TXT","dl_trans_pdf":"📄 PDF",
        "how_it_works":"Comment ça marche",
        "empty_state_title":"Votre texte apparaîtra ici",
        "empty_state_desc":"Téléchargez une image et cliquez sur Extraire.",
        "footer":"{app} v{ver} · EasyOCR · Traitement local.",
        "conf_high":"Élevée","conf_med":"Moyenne","conf_low":"Faible","conf_label":"Confiance — ",
        "stat_words":"mots","stat_lines":"lignes","stat_chars":"car.","stat_blocks":"blocs","stat_lang":"langue",
        "no_text_detected":"Aucun texte détecté. Image plus nette ?",
        "translate_empty":"Extrayez d'abord le texte.",
        "ui_lang_label":"Langue de l'interface",
        "steps":[
            ("1️⃣","Télécharger","PNG, JPG, WEBP — jusqu'à 10 Mo"),
            ("2️⃣","Sélectionner","Choisissez la langue"),
            ("3️⃣","Extraire","OCR IA lit imprimé et manuscrit"),
            ("4️⃣","Modifier","Corrigez les erreurs"),
            ("5️⃣","Exporter","TXT, PDF, Word, Excel, PNG"),
            ("6️⃣","Traduire","Traduisez en 30 langues"),
        ],
    },
    "Spanish": {
        "page_title":"Pic2Docs — Imagen a Texto",
        "tagline":"Imagen → Texto → Cualquier formato",
        "hero_title":"Convierte cualquier imagen en texto — Al instante",
        "hero_desc":"Sube notas manuscritas, documentos o recibos.\nPic2Docs extrae texto con OCR impulsado por IA.",
        "upload_section":"Subir imagen","upload_label":"Suelta aquí o haz clic para explorar",
        "settings_section":"Configuración","ocr_lang_label":"Idioma OCR",
        "ocr_lang_help":"Selecciona el idioma del texto en la imagen.",
        "preprocess_label":"Mejorar imagen",
        "preprocess_help":"Recomendado para fotos de bajo contraste.",
        "preprocess_desc":"Contraste, nitidez y umbral adaptativo.",
        "extract_btn":"🔍 Extraer texto","extracting":"Ejecutando OCR — 30 segundos...",
        "extract_success":"✅ {blocks} bloques con {conf}% de confianza.",
        "file_too_large":"Archivo > {max_mb} MB. Comprima la imagen.",
        "no_upload_title":"Sube una imagen para comenzar",
        "no_upload_desc":"Mejor con imágenes claras y bien iluminadas.",
        "extracted_section":"Texto extraído — Edita antes de exportar",
        "reset_btn":"↩ Restablecer","clear_btn":"🗑 Limpiar",
        "export_section":"Exportar","nothing_to_export":"Nada que exportar.",
        "translate_section":"Traducir","translate_to":"Traducir a",
        "translate_placeholder":"— Seleccionar —","translate_btn":"🌐 Traducir",
        "translating":"Traduciendo a {lang}...","translate_success":"¡Traducción completa!",
        "translate_fail":"Falló: {err}","translated_label":"Traducido ({lang})",
        "dl_txt":"📃 TXT","dl_pdf":"📄 PDF","dl_word":"📝 Word","dl_excel":"📊 Excel","dl_notebook":"🖼 Notebook",
        "dl_trans_txt":"📃 TXT","dl_trans_pdf":"📄 PDF",
        "how_it_works":"Cómo funciona",
        "empty_state_title":"Tu texto aparecerá aquí",
        "empty_state_desc":"Sube una imagen y haz clic en Extraer texto.",
        "footer":"{app} v{ver} · EasyOCR · Procesamiento local.",
        "conf_high":"Alta","conf_med":"Media","conf_low":"Baja","conf_label":"Confianza — ",
        "stat_words":"palabras","stat_lines":"líneas","stat_chars":"chars","stat_blocks":"bloques","stat_lang":"idioma",
        "no_text_detected":"No se detectó texto. ¿Imagen más clara?",
        "translate_empty":"Extrae texto primero.",
        "ui_lang_label":"Idioma de la interfaz",
        "steps":[
            ("1️⃣","Subir","PNG, JPG, WEBP — hasta 10 MB"),
            ("2️⃣","Elegir","Elige el idioma del texto"),
            ("3️⃣","Extraer","OCR IA lee impreso y manuscrito"),
            ("4️⃣","Editar","Corrige errores"),
            ("5️⃣","Exportar","TXT, PDF, Word, Excel, PNG"),
            ("6️⃣","Traducir","Traduce a 30 idiomas"),
        ],
    },
    "Portuguese": {
        "page_title":"Pic2Docs — Conversor de Imagem para Texto",
        "tagline":"Imagem → Texto → Qualquer formato",
        "hero_title":"Converta qualquer imagem em texto — Instantaneamente",
        "hero_desc":"Carregue notas manuscritas, documentos impressos ou recibos.\nPic2Docs extrai texto com OCR baseado em IA.",
        "upload_section":"Carregar imagem","upload_label":"Solte a imagem aqui ou clique para procurar",
        "settings_section":"Configurações","ocr_lang_label":"Idioma OCR",
        "ocr_lang_help":"Selecione o idioma do texto na imagem.",
        "preprocess_label":"Melhorar imagem",
        "preprocess_help":"Recomendado para fotos de baixo contraste.",
        "preprocess_desc":"Aplica correção de contraste, nitidez e limiar adaptativo.",
        "extract_btn":"🔍 Extrair texto","extracting":"Executando OCR — até 30 segundos...",
        "extract_success":"✅ {blocks} blocos extraídos com {conf}% de confiança.",
        "file_too_large":"Arquivo > {max_mb} MB. Comprima a imagem.",
        "no_upload_title":"Carregue uma imagem para começar",
        "no_upload_desc":"Funciona melhor com imagens claras.",
        "extracted_section":"Texto extraído — Edite antes de exportar",
        "reset_btn":"↩ Redefinir","clear_btn":"🗑 Limpar",
        "export_section":"Exportar","nothing_to_export":"Nada para exportar.",
        "translate_section":"Traduzir","translate_to":"Traduzir para",
        "translate_placeholder":"— Selecionar idioma —","translate_btn":"🌐 Traduzir",
        "translating":"Traduzindo para {lang}...","translate_success":"Tradução concluída!",
        "translate_fail":"Falhou: {err}","translated_label":"Traduzido ({lang})",
        "dl_txt":"📃 TXT","dl_pdf":"📄 PDF","dl_word":"📝 Word","dl_excel":"📊 Excel","dl_notebook":"🖼 Notebook",
        "dl_trans_txt":"📃 TXT","dl_trans_pdf":"📄 PDF",
        "how_it_works":"Como funciona",
        "empty_state_title":"Seu texto extraído aparecerá aqui",
        "empty_state_desc":"Carregue uma imagem e clique em Extrair texto.",
        "footer":"{app} v{ver} · EasyOCR · Processamento local.",
        "conf_high":"Alta","conf_med":"Média","conf_low":"Baixa","conf_label":"Confiança — ",
        "stat_words":"palavras","stat_lines":"linhas","stat_chars":"chars","stat_blocks":"blocos","stat_lang":"idioma",
        "no_text_detected":"Nenhum texto detectado. Tente uma imagem mais clara.",
        "translate_empty":"Extraia o texto primeiro.",
        "ui_lang_label":"Idioma da interface",
        "steps":[
            ("1️⃣","Carregar","PNG, JPG, WEBP — até 10 MB"),
            ("2️⃣","Selecionar","Escolha o idioma do texto"),
            ("3️⃣","Extrair","OCR IA lê texto impresso e manuscrito"),
            ("4️⃣","Editar","Corrija erros"),
            ("5️⃣","Exportar","TXT, PDF, Word, Excel ou PNG"),
            ("6️⃣","Traduzir","Traduza para 30 idiomas"),
        ],
    },
    "Chinese": {
        "page_title":"Pic2Docs — 图片转文字",
        "tagline":"图片 → 可编辑文字 → 任意格式",
        "hero_title":"即时将任意图片转换为可编辑文字",
        "hero_desc":"上传手写笔记、印刷文档或收据。\nPic2Docs 使用 AI-OCR 提取文字并导出为任意格式。",
        "upload_section":"上传图片","upload_label":"拖放图片或点击浏览",
        "settings_section":"设置","ocr_lang_label":"OCR 语言",
        "ocr_lang_help":"选择图片中文字的语言。",
        "preprocess_label":"图像增强",
        "preprocess_help":"对低对比度图片有效。",
        "preprocess_desc":"应用对比度校正、锐化和自适应阈值。",
        "extract_btn":"🔍 提取文字","extracting":"OCR 运行中 — 最多 30 秒...",
        "extract_success":"✅ 提取 {blocks} 个文字块，置信度 {conf}%。",
        "file_too_large":"文件超过 {max_mb} MB，请压缩。",
        "no_upload_title":"上传图片以开始",
        "no_upload_desc":"清晰、光线充足的图片效果更佳。",
        "extracted_section":"提取的文字 — 导出前可编辑",
        "reset_btn":"↩ 重置","clear_btn":"🗑 清除",
        "export_section":"导出","nothing_to_export":"无内容可导出。",
        "translate_section":"翻译","translate_to":"翻译为",
        "translate_placeholder":"— 选择语言 —","translate_btn":"🌐 翻译",
        "translating":"正在翻译为 {lang}...","translate_success":"翻译完成！",
        "translate_fail":"翻译失败：{err}","translated_label":"翻译 ({lang})",
        "dl_txt":"📃 TXT","dl_pdf":"📄 PDF","dl_word":"📝 Word","dl_excel":"📊 Excel","dl_notebook":"🖼 记事本",
        "dl_trans_txt":"📃 TXT","dl_trans_pdf":"📄 PDF",
        "how_it_works":"使用方法",
        "empty_state_title":"提取的文字将显示在这里",
        "empty_state_desc":"上传图片并点击提取文字。",
        "footer":"{app} v{ver} · EasyOCR · 本地处理，不存储图片。",
        "conf_high":"高","conf_med":"中","conf_low":"低","conf_label":"置信度 — ",
        "stat_words":"词","stat_lines":"行","stat_chars":"字","stat_blocks":"块","stat_lang":"语言",
        "no_text_detected":"未检测到文字，请尝试更清晰的图片。",
        "translate_empty":"请先提取文字。",
        "ui_lang_label":"界面语言",
        "steps":[
            ("1️⃣","上传","PNG, JPG, WEBP — 最大 10 MB"),
            ("2️⃣","选择","选择图片中的文字语言"),
            ("3️⃣","提取","AI OCR 读取印刷和手写文字"),
            ("4️⃣","编辑","修正错误"),
            ("5️⃣","导出","TXT, PDF, Word, Excel, PNG"),
            ("6️⃣","翻译","翻译成 30 种语言"),
        ],
    },
}

RTL_LANGUAGES = {"Arabic", "Urdu"}
DEFAULT_UI_LANG = "English"

def get_strings(lang: str) -> dict:
    return UI_STRINGS.get(lang, UI_STRINGS["English"])

def is_rtl(lang: str) -> bool:
    return lang in RTL_LANGUAGES
